name: swipe_stack_null_safe
description: Flutter swipe stack widget null safe.
version: 1.0.0
homepage: https://github.com/sayansr26/SwipeStackNullSafe

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter